apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypal-payment-service
  labels:
    app: paypal-payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paypal-payment-service
  template:
    metadata:
      labels:
        app: paypal-payment-service
    spec:
      containers:
        - name: paypal-payment-service
          image: prabeensoti/paypal-payment-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 3
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 130
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
          env:
            - name: PAYMENT_PAYPAL_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app
                  key: PAYMENT_PAYPAL_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: paypal-payment-service
  labels:
    app: paypal-payment-service
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: paypal-payment-service
  type: ClusterIP